name: Building Cobbler packages

on:
  push:
    branches: [ main, release* ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, release* ]

jobs:
  build-centos8-rpms:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build a Rocky Linux 8 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/rpms/build-and-install-rpms.sh rl8 docker/rpms/Rocky_Linux_8/Rocky_Linux_8.dockerfile
      - name: Archive RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms-centos8
          path: |
            rpm-build/*.rpm
  build-fedora34-rpms:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build a Fedora 34 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/rpms/build-and-install-rpms.sh fc34 docker/rpms/Fedora_34/Fedora34.dockerfile
      - name: Archive RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms-fedora-34
          path: |
            rpm-build/*.rpm
  build-debian10-debs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build a Debian 10 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/debs/build-and-install-debs.sh deb10 docker/debs/Debian_10/Debian10.dockerfile
      - name: Archive DEBs
        uses: actions/upload-artifact@v3
        with:
          name: debs-debian10
          path: |
            deb-build/DEBS/all/*.deb
  build-debian11-debs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build a Debian 11 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/debs/build-and-install-debs.sh deb11 docker/debs/Debian_11/Debian11.dockerfile
      - name: Archive DEBs
        uses: actions/upload-artifact@v3
        with:
          name: debs-debian11
          path: |
            deb-build/DEBS/all/*.deb
  build-debian12-debs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build a Debian 12 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/debs/build-and-install-debs.sh deb12 docker/debs/Debian_12/Debian12.dockerfile
      - name: Archive DEBs
        uses: actions/upload-artifact@v3
        with:
          name: debs-debian12
          path: |
            deb-build/DEBS/all/*.deb
  create-release:
    name: Build the release and create a GitHub release
    runs-on: ubuntu-20.04
    needs: [
      build-centos8-rpms,
      build-fedora34-rpms,
      build-debian10-debs,
      build-debian11-debs,
      build-debian12-debs,
    ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        name: Download all built artifacts
        with:
          path: artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/rpms-centos8/*.rpm
            artifacts/debs-debian10/*.deb
            artifacts/debs-debian11/*.deb
            artifacts/debs-debian12/*.deb
            artifacts/rpms-fedora-34/*.rpm
